metrics:
- name: test
  type: counter
  labels:
  - aaa
  - bbb
- name: test2
  type: gauge
  labels:
  - aaa
  - ddd
input_series:
- metrics_name: test
  data:
  - labels:
    - key: aaa
      value: hoge
    - key: bbb
      value: fuga
    values: '1+1x3 0'
  - labels:
    - key: aaa
      value: hoge
    - key: bbb
      value: piyo
    values: '0 0 1+0x4'
- metrics_name: test2
  data:
  - labels:
    - key: aaa
      value: pomb
    - key: ddd
      value: puri
    values: '0 1 0 1 0 1'