spec:
  name: test1
  type: counter
  labels:
  - aaa
  - bbb
data:
- labels:
  - key: aaa
    value: aaa_val1
  - key: bbb
    value: bbb_val1
  sequence: '1+1x2 0'
- labels:
  - key: aaa
    value: aaa_val1
  - key: bbb
    value: bbb_val2
  sequence: '0 1 1+0x3'
---
spec:
  name: test2
  type: gauge
  labels:
  - aaa
  - ccc
data:
- labels:
  - key: aaa
    value: aaa_val2
  - key: ccc
    value: ccc_val1
  sequence: '0 1 0'
