name: Helm

on:
  pull_request:
    branches: [ "main" ]
    paths-ignore:
    - '**.md'
    - 'deploy/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Env setup
      run: make -C e2e setup-by-helm

    - name: Test with helm
      run: make -C e2e test-with-helm
